// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Create a StakerMember account.
//
// # Panics
//
// Panics if .
//
// # Errors
//
// This function will return an error if .
type AddStaker struct {

	// [0] = [WRITE] controller
	//
	// [1] = [] payout
	//
	// [2] = [] validatorMember
	//
	// [3] = [WRITE] stakerMember
	//
	// [4] = [WRITE] receipt
	//
	// [5] = [] staker
	//
	// [6] = [SIGNER] stakeAdmin
	//
	// [7] = [] pcVault
	//
	// [8] = [] clock
	//
	// [9] = [] systemProgram
	//
	// [10] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddStakerInstructionBuilder creates a new `AddStaker` instruction builder.
func NewAddStakerInstructionBuilder() *AddStaker {
	nd := &AddStaker{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetControllerAccount sets the "controller" account.
func (inst *AddStaker) SetControllerAccount(controller ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller).WRITE()
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *AddStaker) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPayoutAccount sets the "payout" account.
func (inst *AddStaker) SetPayoutAccount(payout ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(payout)
	return inst
}

// GetPayoutAccount gets the "payout" account.
func (inst *AddStaker) GetPayoutAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetValidatorMemberAccount sets the "validatorMember" account.
func (inst *AddStaker) SetValidatorMemberAccount(validatorMember ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(validatorMember)
	return inst
}

// GetValidatorMemberAccount gets the "validatorMember" account.
func (inst *AddStaker) GetValidatorMemberAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakerMemberAccount sets the "stakerMember" account.
func (inst *AddStaker) SetStakerMemberAccount(stakerMember ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakerMember).WRITE()
	return inst
}

// GetStakerMemberAccount gets the "stakerMember" account.
func (inst *AddStaker) GetStakerMemberAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReceiptAccount sets the "receipt" account.
func (inst *AddStaker) SetReceiptAccount(receipt ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(receipt).WRITE()
	return inst
}

// GetReceiptAccount gets the "receipt" account.
func (inst *AddStaker) GetReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakerAccount sets the "staker" account.
func (inst *AddStaker) SetStakerAccount(staker ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(staker)
	return inst
}

// GetStakerAccount gets the "staker" account.
func (inst *AddStaker) GetStakerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakeAdminAccount sets the "stakeAdmin" account.
func (inst *AddStaker) SetStakeAdminAccount(stakeAdmin ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakeAdmin).SIGNER()
	return inst
}

// GetStakeAdminAccount gets the "stakeAdmin" account.
func (inst *AddStaker) GetStakeAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPcVaultAccount sets the "pcVault" account.
func (inst *AddStaker) SetPcVaultAccount(pcVault ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(pcVault)
	return inst
}

// GetPcVaultAccount gets the "pcVault" account.
func (inst *AddStaker) GetPcVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetClockAccount sets the "clock" account.
func (inst *AddStaker) SetClockAccount(clock ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *AddStaker) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AddStaker) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AddStaker) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetRentAccount sets the "rent" account.
func (inst *AddStaker) SetRentAccount(rent ag_solanago.PublicKey) *AddStaker {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *AddStaker) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst AddStaker) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddStaker,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddStaker) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddStaker) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Payout is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.ValidatorMember is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakerMember is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Receipt is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Staker is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakeAdmin is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.PcVault is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *AddStaker) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddStaker")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         payout", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("validatorMember", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   stakerMember", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        receipt", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         staker", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     stakeAdmin", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        pcVault", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("          clock", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           rent", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj AddStaker) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *AddStaker) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewAddStakerInstruction declares a new AddStaker instruction with the provided parameters and accounts.
func NewAddStakerInstruction(
	// Accounts:
	controller ag_solanago.PublicKey,
	payout ag_solanago.PublicKey,
	validatorMember ag_solanago.PublicKey,
	stakerMember ag_solanago.PublicKey,
	receipt ag_solanago.PublicKey,
	staker ag_solanago.PublicKey,
	stakeAdmin ag_solanago.PublicKey,
	pcVault ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *AddStaker {
	return NewAddStakerInstructionBuilder().
		SetControllerAccount(controller).
		SetPayoutAccount(payout).
		SetValidatorMemberAccount(validatorMember).
		SetStakerMemberAccount(stakerMember).
		SetReceiptAccount(receipt).
		SetStakerAccount(staker).
		SetStakeAdminAccount(stakeAdmin).
		SetPcVaultAccount(pcVault).
		SetClockAccount(clock).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
