// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CreateStakerManager is the `createStakerManager` instruction.
type CreateStakerManager struct {

	// [0] = [] controller
	//
	// [1] = [WRITE] stakerManager
	//
	// [2] = [] staker
	//
	// [3] = [SIGNER] stakerSigner
	//
	// [4] = [WRITE, SIGNER] stakerAdmin
	//
	// [5] = [] systemProgram
	//
	// [6] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateStakerManagerInstructionBuilder creates a new `CreateStakerManager` instruction builder.
func NewCreateStakerManagerInstructionBuilder() *CreateStakerManager {
	nd := &CreateStakerManager{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetControllerAccount sets the "controller" account.
func (inst *CreateStakerManager) SetControllerAccount(controller ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller)
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *CreateStakerManager) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakerManagerAccount sets the "stakerManager" account.
func (inst *CreateStakerManager) SetStakerManagerAccount(stakerManager ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakerManager).WRITE()
	return inst
}

// GetStakerManagerAccount gets the "stakerManager" account.
func (inst *CreateStakerManager) GetStakerManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakerAccount sets the "staker" account.
func (inst *CreateStakerManager) SetStakerAccount(staker ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(staker)
	return inst
}

// GetStakerAccount gets the "staker" account.
func (inst *CreateStakerManager) GetStakerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakerSignerAccount sets the "stakerSigner" account.
func (inst *CreateStakerManager) SetStakerSignerAccount(stakerSigner ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakerSigner).SIGNER()
	return inst
}

// GetStakerSignerAccount gets the "stakerSigner" account.
func (inst *CreateStakerManager) GetStakerSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetStakerAdminAccount sets the "stakerAdmin" account.
func (inst *CreateStakerManager) SetStakerAdminAccount(stakerAdmin ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(stakerAdmin).WRITE().SIGNER()
	return inst
}

// GetStakerAdminAccount gets the "stakerAdmin" account.
func (inst *CreateStakerManager) GetStakerAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CreateStakerManager) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CreateStakerManager) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRentAccount sets the "rent" account.
func (inst *CreateStakerManager) SetRentAccount(rent ag_solanago.PublicKey) *CreateStakerManager {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *CreateStakerManager) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst CreateStakerManager) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateStakerManager,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateStakerManager) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateStakerManager) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakerManager is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Staker is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakerSigner is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.StakerAdmin is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *CreateStakerManager) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateStakerManager")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("stakerManager", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       staker", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" stakerSigner", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("  stakerAdmin", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj CreateStakerManager) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CreateStakerManager) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCreateStakerManagerInstruction declares a new CreateStakerManager instruction with the provided parameters and accounts.
func NewCreateStakerManagerInstruction(
	// Accounts:
	controller ag_solanago.PublicKey,
	stakerManager ag_solanago.PublicKey,
	staker ag_solanago.PublicKey,
	stakerSigner ag_solanago.PublicKey,
	stakerAdmin ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *CreateStakerManager {
	return NewCreateStakerManagerInstructionBuilder().
		SetControllerAccount(controller).
		SetStakerManagerAccount(stakerManager).
		SetStakerAccount(staker).
		SetStakerSignerAccount(stakerSigner).
		SetStakerAdminAccount(stakerAdmin).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
