// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CreateBidReceipt is the `createBidReceipt` instruction.
type CreateBidReceipt struct {

	// [0] = [] controller
	//
	// [1] = [WRITE] pipeline
	//
	// [2] = [] payout
	//
	// [3] = [WRITE] bidReceipt
	//
	// [4] = [WRITE, SIGNER] bidder
	//
	// [5] = [] clock
	//
	// [6] = [] systemProgram
	//
	// [7] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateBidReceiptInstructionBuilder creates a new `CreateBidReceipt` instruction builder.
func NewCreateBidReceiptInstructionBuilder() *CreateBidReceipt {
	nd := &CreateBidReceipt{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetControllerAccount sets the "controller" account.
func (inst *CreateBidReceipt) SetControllerAccount(controller ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller)
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *CreateBidReceipt) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPipelineAccount sets the "pipeline" account.
func (inst *CreateBidReceipt) SetPipelineAccount(pipeline ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(pipeline).WRITE()
	return inst
}

// GetPipelineAccount gets the "pipeline" account.
func (inst *CreateBidReceipt) GetPipelineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPayoutAccount sets the "payout" account.
func (inst *CreateBidReceipt) SetPayoutAccount(payout ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(payout)
	return inst
}

// GetPayoutAccount gets the "payout" account.
func (inst *CreateBidReceipt) GetPayoutAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBidReceiptAccount sets the "bidReceipt" account.
func (inst *CreateBidReceipt) SetBidReceiptAccount(bidReceipt ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(bidReceipt).WRITE()
	return inst
}

// GetBidReceiptAccount gets the "bidReceipt" account.
func (inst *CreateBidReceipt) GetBidReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetBidderAccount sets the "bidder" account.
func (inst *CreateBidReceipt) SetBidderAccount(bidder ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(bidder).WRITE().SIGNER()
	return inst
}

// GetBidderAccount gets the "bidder" account.
func (inst *CreateBidReceipt) GetBidderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetClockAccount sets the "clock" account.
func (inst *CreateBidReceipt) SetClockAccount(clock ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *CreateBidReceipt) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CreateBidReceipt) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CreateBidReceipt) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentAccount sets the "rent" account.
func (inst *CreateBidReceipt) SetRentAccount(rent ag_solanago.PublicKey) *CreateBidReceipt {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *CreateBidReceipt) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst CreateBidReceipt) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateBidReceipt,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateBidReceipt) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateBidReceipt) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Pipeline is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Payout is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BidReceipt is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Bidder is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *CreateBidReceipt) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateBidReceipt")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     pipeline", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       payout", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   bidReceipt", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       bidder", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        clock", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj CreateBidReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CreateBidReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCreateBidReceiptInstruction declares a new CreateBidReceipt instruction with the provided parameters and accounts.
func NewCreateBidReceiptInstruction(
	// Accounts:
	controller ag_solanago.PublicKey,
	pipeline ag_solanago.PublicKey,
	payout ag_solanago.PublicKey,
	bidReceipt ag_solanago.PublicKey,
	bidder ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *CreateBidReceipt {
	return NewCreateBidReceiptInstructionBuilder().
		SetControllerAccount(controller).
		SetPipelineAccount(pipeline).
		SetPayoutAccount(payout).
		SetBidReceiptAccount(bidReceipt).
		SetBidderAccount(bidder).
		SetClockAccount(clock).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
