// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// StakerWithdrawReceipt is the `stakerWithdrawReceipt` instruction.
type StakerWithdrawReceipt struct {

	// [0] = [WRITE] controller
	//
	// [1] = [WRITE] pipeline
	//
	// [2] = [WRITE] pcVault
	//
	// [3] = [] payout
	//
	// [4] = [] validatorManager
	//
	// [5] = [] stakerManager
	//
	// [6] = [WRITE] receipt
	//
	// [7] = [WRITE] stakerReceipt
	//
	// [8] = [WRITE] stakerFund
	//
	// [9] = [WRITE, SIGNER] stakerAdmin
	//
	// [10] = [] tokenProgram
	//
	// [11] = [] clock
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakerWithdrawReceiptInstructionBuilder creates a new `StakerWithdrawReceipt` instruction builder.
func NewStakerWithdrawReceiptInstructionBuilder() *StakerWithdrawReceipt {
	nd := &StakerWithdrawReceipt{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
	return nd
}

// SetControllerAccount sets the "controller" account.
func (inst *StakerWithdrawReceipt) SetControllerAccount(controller ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller).WRITE()
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *StakerWithdrawReceipt) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPipelineAccount sets the "pipeline" account.
func (inst *StakerWithdrawReceipt) SetPipelineAccount(pipeline ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(pipeline).WRITE()
	return inst
}

// GetPipelineAccount gets the "pipeline" account.
func (inst *StakerWithdrawReceipt) GetPipelineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPcVaultAccount sets the "pcVault" account.
func (inst *StakerWithdrawReceipt) SetPcVaultAccount(pcVault ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(pcVault).WRITE()
	return inst
}

// GetPcVaultAccount gets the "pcVault" account.
func (inst *StakerWithdrawReceipt) GetPcVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayoutAccount sets the "payout" account.
func (inst *StakerWithdrawReceipt) SetPayoutAccount(payout ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payout)
	return inst
}

// GetPayoutAccount gets the "payout" account.
func (inst *StakerWithdrawReceipt) GetPayoutAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetValidatorManagerAccount sets the "validatorManager" account.
func (inst *StakerWithdrawReceipt) SetValidatorManagerAccount(validatorManager ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(validatorManager)
	return inst
}

// GetValidatorManagerAccount gets the "validatorManager" account.
func (inst *StakerWithdrawReceipt) GetValidatorManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakerManagerAccount sets the "stakerManager" account.
func (inst *StakerWithdrawReceipt) SetStakerManagerAccount(stakerManager ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(stakerManager)
	return inst
}

// GetStakerManagerAccount gets the "stakerManager" account.
func (inst *StakerWithdrawReceipt) GetStakerManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetReceiptAccount sets the "receipt" account.
func (inst *StakerWithdrawReceipt) SetReceiptAccount(receipt ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(receipt).WRITE()
	return inst
}

// GetReceiptAccount gets the "receipt" account.
func (inst *StakerWithdrawReceipt) GetReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakerReceiptAccount sets the "stakerReceipt" account.
func (inst *StakerWithdrawReceipt) SetStakerReceiptAccount(stakerReceipt ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakerReceipt).WRITE()
	return inst
}

// GetStakerReceiptAccount gets the "stakerReceipt" account.
func (inst *StakerWithdrawReceipt) GetStakerReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetStakerFundAccount sets the "stakerFund" account.
func (inst *StakerWithdrawReceipt) SetStakerFundAccount(stakerFund ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(stakerFund).WRITE()
	return inst
}

// GetStakerFundAccount gets the "stakerFund" account.
func (inst *StakerWithdrawReceipt) GetStakerFundAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakerAdminAccount sets the "stakerAdmin" account.
func (inst *StakerWithdrawReceipt) SetStakerAdminAccount(stakerAdmin ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakerAdmin).WRITE().SIGNER()
	return inst
}

// GetStakerAdminAccount gets the "stakerAdmin" account.
func (inst *StakerWithdrawReceipt) GetStakerAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *StakerWithdrawReceipt) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *StakerWithdrawReceipt) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetClockAccount sets the "clock" account.
func (inst *StakerWithdrawReceipt) SetClockAccount(clock ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *StakerWithdrawReceipt) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

func (inst StakerWithdrawReceipt) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_StakerWithdrawReceipt,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst StakerWithdrawReceipt) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *StakerWithdrawReceipt) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Pipeline is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PcVault is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payout is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ValidatorManager is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.StakerManager is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Receipt is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakerReceipt is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.StakerFund is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.StakerAdmin is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Clock is not set")
		}
	}
	return nil
}

func (inst *StakerWithdrawReceipt) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("StakerWithdrawReceipt")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=12]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        pipeline", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         pcVault", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("          payout", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("validatorManager", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("   stakerManager", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         receipt", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("   stakerReceipt", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("      stakerFund", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("     stakerAdmin", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("           clock", inst.AccountMetaSlice.Get(11)))
					})
				})
		})
}

func (obj StakerWithdrawReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *StakerWithdrawReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewStakerWithdrawReceiptInstruction declares a new StakerWithdrawReceipt instruction with the provided parameters and accounts.
func NewStakerWithdrawReceiptInstruction(
	// Accounts:
	controller ag_solanago.PublicKey,
	pipeline ag_solanago.PublicKey,
	pcVault ag_solanago.PublicKey,
	payout ag_solanago.PublicKey,
	validatorManager ag_solanago.PublicKey,
	stakerManager ag_solanago.PublicKey,
	receipt ag_solanago.PublicKey,
	stakerReceipt ag_solanago.PublicKey,
	stakerFund ag_solanago.PublicKey,
	stakerAdmin ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	clock ag_solanago.PublicKey) *StakerWithdrawReceipt {
	return NewStakerWithdrawReceiptInstructionBuilder().
		SetControllerAccount(controller).
		SetPipelineAccount(pipeline).
		SetPcVaultAccount(pcVault).
		SetPayoutAccount(payout).
		SetValidatorManagerAccount(validatorManager).
		SetStakerManagerAccount(stakerManager).
		SetReceiptAccount(receipt).
		SetStakerReceiptAccount(stakerReceipt).
		SetStakerFundAccount(stakerFund).
		SetStakerAdminAccount(stakerAdmin).
		SetTokenProgramAccount(tokenProgram).
		SetClockAccount(clock)
}
