// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// StakerWithdrawReceipt is the `stakerWithdrawReceipt` instruction.
type StakerWithdrawReceipt struct {

	// [0] = [WRITE] controller
	//
	// [1] = [WRITE] pipeline
	//
	// [2] = [WRITE] pcVault
	//
	// [3] = [] payout
	//
	// [4] = [] validatorMember
	//
	// [5] = [WRITE] receipt
	//
	// [6] = [WRITE] stakerMember
	//
	// [7] = [WRITE] stakerFund
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] clock
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakerWithdrawReceiptInstructionBuilder creates a new `StakerWithdrawReceipt` instruction builder.
func NewStakerWithdrawReceiptInstructionBuilder() *StakerWithdrawReceipt {
	nd := &StakerWithdrawReceipt{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetControllerAccount sets the "controller" account.
func (inst *StakerWithdrawReceipt) SetControllerAccount(controller ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller).WRITE()
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *StakerWithdrawReceipt) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPipelineAccount sets the "pipeline" account.
func (inst *StakerWithdrawReceipt) SetPipelineAccount(pipeline ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(pipeline).WRITE()
	return inst
}

// GetPipelineAccount gets the "pipeline" account.
func (inst *StakerWithdrawReceipt) GetPipelineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPcVaultAccount sets the "pcVault" account.
func (inst *StakerWithdrawReceipt) SetPcVaultAccount(pcVault ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(pcVault).WRITE()
	return inst
}

// GetPcVaultAccount gets the "pcVault" account.
func (inst *StakerWithdrawReceipt) GetPcVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayoutAccount sets the "payout" account.
func (inst *StakerWithdrawReceipt) SetPayoutAccount(payout ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payout)
	return inst
}

// GetPayoutAccount gets the "payout" account.
func (inst *StakerWithdrawReceipt) GetPayoutAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetValidatorMemberAccount sets the "validatorMember" account.
func (inst *StakerWithdrawReceipt) SetValidatorMemberAccount(validatorMember ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(validatorMember)
	return inst
}

// GetValidatorMemberAccount gets the "validatorMember" account.
func (inst *StakerWithdrawReceipt) GetValidatorMemberAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetReceiptAccount sets the "receipt" account.
func (inst *StakerWithdrawReceipt) SetReceiptAccount(receipt ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(receipt).WRITE()
	return inst
}

// GetReceiptAccount gets the "receipt" account.
func (inst *StakerWithdrawReceipt) GetReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakerMemberAccount sets the "stakerMember" account.
func (inst *StakerWithdrawReceipt) SetStakerMemberAccount(stakerMember ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakerMember).WRITE()
	return inst
}

// GetStakerMemberAccount gets the "stakerMember" account.
func (inst *StakerWithdrawReceipt) GetStakerMemberAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakerFundAccount sets the "stakerFund" account.
func (inst *StakerWithdrawReceipt) SetStakerFundAccount(stakerFund ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakerFund).WRITE()
	return inst
}

// GetStakerFundAccount gets the "stakerFund" account.
func (inst *StakerWithdrawReceipt) GetStakerFundAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *StakerWithdrawReceipt) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *StakerWithdrawReceipt) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetClockAccount sets the "clock" account.
func (inst *StakerWithdrawReceipt) SetClockAccount(clock ag_solanago.PublicKey) *StakerWithdrawReceipt {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *StakerWithdrawReceipt) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst StakerWithdrawReceipt) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_StakerWithdrawReceipt,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst StakerWithdrawReceipt) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *StakerWithdrawReceipt) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Pipeline is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PcVault is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payout is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ValidatorMember is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Receipt is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakerMember is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakerFund is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Clock is not set")
		}
	}
	return nil
}

func (inst *StakerWithdrawReceipt) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("StakerWithdrawReceipt")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       pipeline", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        pcVault", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         payout", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("validatorMember", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        receipt", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("   stakerMember", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("     stakerFund", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("   tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          clock", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj StakerWithdrawReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *StakerWithdrawReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewStakerWithdrawReceiptInstruction declares a new StakerWithdrawReceipt instruction with the provided parameters and accounts.
func NewStakerWithdrawReceiptInstruction(
	// Accounts:
	controller ag_solanago.PublicKey,
	pipeline ag_solanago.PublicKey,
	pcVault ag_solanago.PublicKey,
	payout ag_solanago.PublicKey,
	validatorMember ag_solanago.PublicKey,
	receipt ag_solanago.PublicKey,
	stakerMember ag_solanago.PublicKey,
	stakerFund ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	clock ag_solanago.PublicKey) *StakerWithdrawReceipt {
	return NewStakerWithdrawReceiptInstructionBuilder().
		SetControllerAccount(controller).
		SetPipelineAccount(pipeline).
		SetPcVaultAccount(pcVault).
		SetPayoutAccount(payout).
		SetValidatorMemberAccount(validatorMember).
		SetReceiptAccount(receipt).
		SetStakerMemberAccount(stakerMember).
		SetStakerFundAccount(stakerFund).
		SetTokenProgramAccount(tokenProgram).
		SetClockAccount(clock)
}
