// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solmate_cba

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/SolmateDev/solana-go"
	ag_format "github.com/SolmateDev/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateReceipt is the `updateReceipt` instruction.
type UpdateReceipt struct {
	TxSent *uint32
	LastTx *[32]uint8

	// [0] = [] controller
	//
	// [1] = [WRITE] pipeline
	//
	// [2] = [WRITE] payout
	//
	// [3] = [WRITE] validatorMember
	//
	// [4] = [WRITE] receipt
	//
	// [5] = [SIGNER] pipelineAdmin
	//
	// [6] = [SIGNER] validatorAdmin
	//
	// [7] = [] clock
	//
	// [8] = [] systemProgram
	//
	// [9] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateReceiptInstructionBuilder creates a new `UpdateReceipt` instruction builder.
func NewUpdateReceiptInstructionBuilder() *UpdateReceipt {
	nd := &UpdateReceipt{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetTxSent sets the "txSent" parameter.
func (inst *UpdateReceipt) SetTxSent(txSent uint32) *UpdateReceipt {
	inst.TxSent = &txSent
	return inst
}

// SetLastTx sets the "lastTx" parameter.
func (inst *UpdateReceipt) SetLastTx(lastTx [32]uint8) *UpdateReceipt {
	inst.LastTx = &lastTx
	return inst
}

// SetControllerAccount sets the "controller" account.
func (inst *UpdateReceipt) SetControllerAccount(controller ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(controller)
	return inst
}

// GetControllerAccount gets the "controller" account.
func (inst *UpdateReceipt) GetControllerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPipelineAccount sets the "pipeline" account.
func (inst *UpdateReceipt) SetPipelineAccount(pipeline ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(pipeline).WRITE()
	return inst
}

// GetPipelineAccount gets the "pipeline" account.
func (inst *UpdateReceipt) GetPipelineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPayoutAccount sets the "payout" account.
func (inst *UpdateReceipt) SetPayoutAccount(payout ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(payout).WRITE()
	return inst
}

// GetPayoutAccount gets the "payout" account.
func (inst *UpdateReceipt) GetPayoutAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetValidatorMemberAccount sets the "validatorMember" account.
func (inst *UpdateReceipt) SetValidatorMemberAccount(validatorMember ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(validatorMember).WRITE()
	return inst
}

// GetValidatorMemberAccount gets the "validatorMember" account.
func (inst *UpdateReceipt) GetValidatorMemberAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReceiptAccount sets the "receipt" account.
func (inst *UpdateReceipt) SetReceiptAccount(receipt ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(receipt).WRITE()
	return inst
}

// GetReceiptAccount gets the "receipt" account.
func (inst *UpdateReceipt) GetReceiptAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPipelineAdminAccount sets the "pipelineAdmin" account.
func (inst *UpdateReceipt) SetPipelineAdminAccount(pipelineAdmin ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(pipelineAdmin).SIGNER()
	return inst
}

// GetPipelineAdminAccount gets the "pipelineAdmin" account.
func (inst *UpdateReceipt) GetPipelineAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetValidatorAdminAccount sets the "validatorAdmin" account.
func (inst *UpdateReceipt) SetValidatorAdminAccount(validatorAdmin ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(validatorAdmin).SIGNER()
	return inst
}

// GetValidatorAdminAccount gets the "validatorAdmin" account.
func (inst *UpdateReceipt) GetValidatorAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetClockAccount sets the "clock" account.
func (inst *UpdateReceipt) SetClockAccount(clock ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *UpdateReceipt) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateReceipt) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateReceipt) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetRentAccount sets the "rent" account.
func (inst *UpdateReceipt) SetRentAccount(rent ag_solanago.PublicKey) *UpdateReceipt {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *UpdateReceipt) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst UpdateReceipt) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateReceipt,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateReceipt) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateReceipt) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.TxSent == nil {
			return errors.New("TxSent parameter is not set")
		}
		if inst.LastTx == nil {
			return errors.New("LastTx parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Controller is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Pipeline is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Payout is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ValidatorMember is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Receipt is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.PipelineAdmin is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.ValidatorAdmin is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *UpdateReceipt) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateReceipt")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("TxSent", *inst.TxSent))
						paramsBranch.Child(ag_format.Param("LastTx", *inst.LastTx))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     controller", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       pipeline", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         payout", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("validatorMember", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        receipt", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("  pipelineAdmin", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta(" validatorAdmin", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          clock", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("           rent", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj UpdateReceipt) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `TxSent` param:
	err = encoder.Encode(obj.TxSent)
	if err != nil {
		return err
	}
	// Serialize `LastTx` param:
	err = encoder.Encode(obj.LastTx)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateReceipt) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `TxSent`:
	err = decoder.Decode(&obj.TxSent)
	if err != nil {
		return err
	}
	// Deserialize `LastTx`:
	err = decoder.Decode(&obj.LastTx)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateReceiptInstruction declares a new UpdateReceipt instruction with the provided parameters and accounts.
func NewUpdateReceiptInstruction(
	// Parameters:
	txSent uint32,
	lastTx [32]uint8,
	// Accounts:
	controller ag_solanago.PublicKey,
	pipeline ag_solanago.PublicKey,
	payout ag_solanago.PublicKey,
	validatorMember ag_solanago.PublicKey,
	receipt ag_solanago.PublicKey,
	pipelineAdmin ag_solanago.PublicKey,
	validatorAdmin ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *UpdateReceipt {
	return NewUpdateReceiptInstructionBuilder().
		SetTxSent(txSent).
		SetLastTx(lastTx).
		SetControllerAccount(controller).
		SetPipelineAccount(pipeline).
		SetPayoutAccount(payout).
		SetValidatorMemberAccount(validatorMember).
		SetReceiptAccount(receipt).
		SetPipelineAdminAccount(pipelineAdmin).
		SetValidatorAdminAccount(validatorAdmin).
		SetClockAccount(clock).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
